// Role-based access control configuration
export const ROLES = {
  OWNER: "owner",
  SUPERVISOR: "supervisor",
};

export const PERMISSIONS = {
  REPORTS: {
    READ: [ROLES.OWNER, ROLES.SUPERVISOR],
    EXPORT: [ROLES.OWNER],
  },
  COSTS: {
    READ: [ROLES.OWNER, ROLES.SUPERVISOR],
    WRITE: [ROLES.OWNER],
  },
  LABOR: {
    READ: [ROLES.OWNER, ROLES.SUPERVISOR],
    WRITE: [ROLES.OWNER, ROLES.SUPERVISOR],
  },
  LABORERS: {
    CREATE: [ROLES.OWNER, ROLES.SUPERVISOR],
    READ: [ROLES.OWNER, ROLES.SUPERVISOR],
    UPDATE: [ROLES.OWNER, ROLES.SUPERVISOR],
    DELETE: [ROLES.OWNER],
  },
  WORK_ASSIGNMENTS: {
    CREATE: [ROLES.OWNER, ROLES.SUPERVISOR],
    READ: [ROLES.OWNER, ROLES.SUPERVISOR],
    UPDATE: [ROLES.OWNER, ROLES.SUPERVISOR],
    DELETE: [ROLES.OWNER],
    ASSIGN: [ROLES.OWNER, ROLES.SUPERVISOR],
  },
  DAILY_LOGS: {
    READ: [ROLES.OWNER, ROLES.SUPERVISOR],
    WRITE: [ROLES.SUPERVISOR],
  },
};

export default {
  ROLES,
  PERMISSIONS,
};
